package com.company.excepciones;

public class Finally {

    public static void main(String[] args) {

        // Connection conexion = null;
        try {
            // abrir conexi贸n a base de datos
            // recuperar datos
            // SELECT * FROM customers;
            int result = 5 / 0;
            // conexion.close;

        } catch (NullPointerException e) {
            System.out.println("Se ha producido un error.");
            // conexion.close();

        } finally {
            // cerrar conexi贸n a base de datos
            // si conexi贸n abierta, entonces conexion.close();
            System.out.println("Cerrando conexi贸n desde finally.");
        }

        System.out.println("Fin del programa.");
    }
}
